#!/bin/sh

TAG="latest"

# build
docker build -t nbtri/alpine-redis:$TAG .
echo "\n-> Build success\n"

# image push
if [ "$#" -ne 0 ] && [ "$1" = "push" ]; then
	docker push nbtri/alpine-redis:$TAG
fi